- name: Create instance(s)
  hosts: localhost
  gather_facts: False

  vars:
    service_account_email: ansible2@eksamen-pgr301.iam.gserviceaccount.com
    credentials_file: ~/gc_credentials.json
    project_id: eksamen-pgr301
    machine_type: n1-standard-1
    image: debian-9

  tasks:

    - name: Launch instances
      gce:
        instance_names: instance-pgr301
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        state: present
      register: gce

  post_tasks:
    - name: Wait for SSH
      wait_for: delay=1 host={{ item.public_ip }} port=22 state=started timeout=30
      with_items: "{{ gcea.instance_data }}"
    - name: Save host data
      add_host: hostname={{ item.public_ip }} groupname=gce_instances_ips
      with_items: "{{ gcea.instance_data }}"