- name: Create instance(s)
  hosts: localhost
  gather_facts: False

  vars:
    service_account_email: ansible-1@eksamen-pgr301.iam.gserviceaccount.com
    credentials_file: ~/gc_credentials.json
    project_id: eksamen-pgr301
    machine_type: n1-standard-1
    zone: europe-west1-b
    image: debian-9

  tasks:

    - name: Launch instances
      gce:
        instance_names: PGR301
        zone: "{{ zone }}"
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        state: present

  post_tasks:
    - name: Wait for SSH for instances in first zone
      wait_for: delay=1 host={{ item.public_ip }} port=22 state=started timeout=30
      with_items: "{{ gcea.instance_data }}"
    - name: Save host data for first zone
      add_host: hostname={{ item.public_ip }} groupname=gce_instances_ips
      with_items: "{{ gcea.instance_data }}"